/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/openfluke/loom/welvet/cabi */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "acceleration_ext.go"

#include <stdlib.h>
#include <stdint.h>

typedef struct {
	uint32_t BatchSize;
	uint32_t InputSize;
	uint32_t OutputSize;
	uint32_t TileSize;
} WGPUDenseParams;

typedef struct {
	uint32_t NumHeads;
	uint32_t NumKVHeads;
	uint32_t HeadDim;
	uint32_t SeqLen;
	uint32_t KVOffset;
	uint32_t MaxSeqLen;
	uint32_t TileSize;
	uint32_t Padding;
} WGPUMHAParams;

typedef struct {
	uint32_t Size;
	float Epsilon;
} WGPURMSNormParams;

typedef struct {
	uint32_t Offset;
	uint32_t HeadDim;
	uint32_t MaxSeqLen;
	uint32_t NumKVHeads;
	uint32_t NumTokens;
} WGPUKVParams;

typedef struct {
	uint32_t SeqLen;
	uint32_t HeadDim;
	uint32_t NumHeads;
	uint32_t Offset;
	float Theta;
} WGPURoPEParams;

typedef struct {
	uint32_t VocabSize;
	uint32_t HiddenSize;
	uint32_t NumTokens;
	uint32_t Padding;
} WGPUEmbeddingParams;

#line 1 "cgo-generated-wrapper"

#line 3 "acceleration_wgpu_exports.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "core_io_parity_exports.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "engine_ext.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "evolution_ext.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "gpu_backward_ext.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "inference.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "io_ext.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "layers_ext.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "llm_ext.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "main.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "persistence_ext.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "structs_ext.go"

#include <stdlib.h>
#include <stdint.h>

typedef struct {
	int Z, Y, X, L;
	int Type;
	int Activation;
	int DType;
	int InputHeight, InputWidth, InputDepth;
	int OutputHeight, OutputWidth, OutputDepth;
	int InputChannels, Filters, KernelSize, Stride, Padding;
	int NumHeads, NumKVHeads, DModel, SeqLength;
	int VocabSize, EmbeddingDim;
	int NumClusters;
	int UseTiling, TileSize;
} LoomLayerSpec;

typedef struct {
	float Avg;
	float Max;
	float Min;
	int Active;
	int Total;
} LoomLayerStats;

typedef struct {
	int DType;
	int Rank;
	int64_t Shape[8];
} LoomTensorMeta;

typedef struct {
	const char* Name;
	int DType;
	int Rank;
	int64_t Shape[8];
	uint64_t DataOffset;
	uint64_t DataLength;
} LoomTensorInfo;

typedef struct {
	int NumTensors;
	LoomTensorInfo* Tensors;
} LoomSafetensorsHeader;

typedef struct {
	const char* ID;
	const char* Name;
	int GridDepth;
	int GridRows;
	int GridCols;
} LoomNetworkBlueprint;

typedef struct {
	uint32_t BatchSize;
	uint32_t InC;
	uint32_t InL;
	uint32_t OutC;
	uint32_t OutL;
	uint32_t KSize;
	uint32_t Stride;
	uint32_t Padding;
	float Scale;
	uint32_t _Pad[7];
} LoomCNN1ScaleParams;

typedef struct {
	uint32_t BatchSize;
	uint32_t InC, InH, InW;
	uint32_t OutC, OutH, OutW;
	uint32_t KH, KW;
	uint32_t StrideH, StrideW;
	uint32_t PadH, PadW;
	float Scale;
	uint32_t _Pad[1];
} LoomCNN2ScaleParams;

typedef struct {
	uint32_t BatchSize;
	uint32_t InC, InD, InH, InW;
	uint32_t OutC, OutD, OutH, OutW;
	uint32_t KD, KH, KW;
	uint32_t SD, SH, SW;
	uint32_t PD, PH, PW;
	float Scale;
	uint32_t _Pad[1];
} LoomCNN3ScaleParams;

typedef struct {
	uint32_t BatchSize;
	uint32_t InputSize;
	uint32_t OutputSize;
	uint32_t TileSize;
	float Scale;
	uint32_t Activation;
} LoomDenseScaleParams;

typedef struct {
	uint32_t BatchSize;
	uint32_t InC;
	uint32_t InL;
	uint32_t Filters;
	uint32_t OutL;
	uint32_t KSize;
	uint32_t Stride;
	uint32_t Padding;
	uint32_t Activation;
	uint32_t _Pad[7];
} LoomCNN1Bwd1DParams;

typedef struct {
	uint32_t BatchSize;
	uint32_t InC, InH, InW;
	uint32_t Filters;
	uint32_t OutH, OutW;
	uint32_t KSize;
	uint32_t Stride;
	uint32_t Padding;
	uint32_t Activation;
	uint32_t _Pad[3];
} LoomCNN2Bwd2DParams;

typedef struct {
	uint32_t BatchSize;
	uint32_t InC, InD, InH, InW;
	uint32_t Filters;
	uint32_t OutD, OutH, OutW;
	uint32_t KD, KH, KW;
	uint32_t SD, SH, SW;
	uint32_t PD, PH, PW;
	uint32_t Activation;
	uint32_t Pad;
} LoomCNN3Backward3DParams;

typedef struct {
	void* Buffer;
	uint64_t Offset;
	uint64_t Size;
} LoomBufferBinding;

typedef struct {
	uint64_t HeaderSize;
} LoomTensorMetaHeader;



#line 1 "cgo-generated-wrapper"

#line 3 "tanhi_ext.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "tokenizer_ext.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "training_ext.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "transformer_ext.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void LoomDestroyWGPU(long long networkHandle);
extern int LoomIsGPU(long long networkHandle);
extern int LoomGetGPUSCTileSize(long long networkHandle);
extern int LoomGetGPUMCTileSize(long long networkHandle);
extern char* LoomDispatchDenseTiled(long long networkHandle, int tileSize, int batchSize, int inputSize, int outputSize, unsigned int activation, float scale, long long inputHandle, long long weightHandle, long long biasHandle, long long outputHandle);
extern char* LoomDispatchDenseScaled(long long networkHandle, int batchSize, int inputSize, int outputSize, unsigned int activation, float scale, long long inputHandle, long long weightHandle, long long biasHandle, long long outputHandle);
extern char* LoomDispatchCNN1Scaled(long long networkHandle, int batchSize, int inC, int inL, int outC, int outL, int kSize, int stride, int padding, float scale, long long inputHandle, long long weightHandle, long long outputHandle);
extern char* LoomDispatchCNN2Scaled(long long networkHandle, int batchSize, int inC, int inH, int inW, int outC, int outH, int outW, int kH, int kW, int strideH, int strideW, int padH, int padW, float scale, long long inputHandle, long long weightHandle, long long outputHandle);
extern char* LoomDispatchCNN3Scaled(long long networkHandle, int batchSize, int inC, int inD, int inH, int inW, int outC, int outD, int outH, int outW, int kD, int kH, int kW, int sD, int sH, int sW, int pD, int pH, int pW, float scale, long long inputHandle, long long weightHandle, long long outputHandle);
extern char* LoomDispatchAdd(long long networkHandle, int size, long long aHandle, long long bHandle, long long resHandle);
extern char* LoomDispatchSwiGLUWithActCache(long long networkHandle, int batchSize, int inputSize, int outputSize, long long inputHandle, long long gateHandle, long long upHandle, long long gateBiasHandle, long long upBiasHandle, long long outputHandle, long long gateOutHandle, long long upOutHandle, int tileSize);
extern char* LoomDispatchLSTMStepPreAct(long long networkHandle, int batchSize, int inputSize, int hiddenSize, long long inputHandle, long long hPrevHandle, long long cPrevHandle, long long weightHandle, long long hCurrHandle, long long cCurrHandle, long long preActHandle);
extern void LoomDenseGPUTileSizes(long long networkHandle, int dtype, int* scTile, int* mcTile);
extern void LoomDenseGPUTileSizesFromContext(long long networkHandle, int dtype, int* scTile, int* mcTile);
extern void LoomCNN1GPUTileSizes(long long networkHandle, int dtype, int* scTile, int* mcTile);
extern void LoomCNN2GPUTileSizes(long long networkHandle, int dtype, int* scTile, int* mcTile);
extern void LoomCNN3GPUTileSizes(long long networkHandle, int dtype, int* scTile, int* mcTile);
extern void LoomSwiGLUGPUTileSizes(long long networkHandle, int dtype, int* scTile, int* mcTile);
extern void LoomMHAGPUTileSizes(long long networkHandle, int headDim, int dtype, int* scTile, int* mcTile);
extern char* LoomSyncWeightsFromGPU(long long networkHandle);
extern char* LoomShaderTiledSwiGLUActCache(int tileSize);
extern char* LoomInitWGPU(long long networkHandle);
extern char* LoomSyncToGPU(long long networkHandle);
extern void LoomSyncToCPU(long long networkHandle);
extern void LoomSyncInferenceWeights(long long networkHandle);
extern char* LoomDispatchDense(long long networkHandle, int batchSize, int inputSize, int outputSize, long long inputHandle, long long weightHandle, long long outputHandle, int tileSize);
extern char* LoomDispatchDenseQ4(long long networkHandle, int batchSize, int inputSize, int outputSize, long long inputHandle, long long scaleHandle, long long weightHandle, long long outputHandle, int tileSize);
extern char* LoomDispatchMHA(long long networkHandle, int numHeads, int numKVHeads, int headDim, int seqLen, int kvOffset, int maxSeqLen, long long qHandle, long long kHandle, long long vHandle, long long oHandle, int tileSize);
extern char* LoomDispatchSwiGLU(long long networkHandle, int batchSize, int inputSize, int outputSize, long long inputHandle, long long gateHandle, long long upHandle, long long outputHandle, int tileSize);
extern char* LoomDispatchRMSNorm(long long networkHandle, int batchSize, int size, float epsilon, long long inputHandle, long long weightHandle, long long outputHandle);
extern char* LoomDispatchKVUpdate(long long networkHandle, int offset, int headDim, int maxSeqLen, int numKVHeads, int numTokens, long long kCacheHandle, long long vCacheHandle, long long newKHandle, long long newVHandle);
extern char* LoomDispatchResidual(long long networkHandle, int size, long long inputHandle, long long residualHandle);
extern char* LoomDispatchRoPE(long long networkHandle, int seqLen, int headDim, int numHeads, int offset, float theta, long long targetHandle);
extern char* LoomDispatchEmbedding(long long networkHandle, int vocabSize, int hiddenSize, int numTokens, long long indicesHandle, long long weightsHandle, long long outputHandle);
extern char* LoomDispatchRNNStep(long long networkHandle, int batchSize, int inputSize, int hiddenSize, long long inputHandle, long long hPrevHandle, long long wIHHandle, long long wHHHandle, long long biasHandle, long long hCurrHandle);
extern char* LoomDispatchLSTMStep(long long networkHandle, int batchSize, int inputSize, int hiddenSize, long long inputHandle, long long hPrevHandle, long long cPrevHandle, long long weightHandle, long long hCurrHandle, long long cCurrHandle);
extern char* LoomDispatchCNN1(long long networkHandle, int batchSize, int inC, int inL, int outC, int outL, int kSize, int stride, int padding, long long inputHandle, long long weightHandle, long long outputHandle);
extern char* LoomDispatchCNN2(long long networkHandle, int batchSize, int inC, int inH, int inW, int outC, int outH, int outW, int kH, int kW, int strideH, int strideW, int padH, int padW, long long inputHandle, long long weightHandle, long long outputHandle);
extern char* LoomDispatchCNN3(long long networkHandle, int batchSize, int inC, int inD, int inH, int inW, int outC, int outD, int outH, int outW, int kD, int kH, int kW, int sD, int sH, int sW, int pD, int pH, int pW, long long inputHandle, long long weightHandle, long long outputHandle);
extern char* LoomDispatchSwiGLUQ4(long long networkHandle, int batchSize, int inputSize, int outputSize, long long inputHandle, long long gateScaleHandle, long long gateWeightHandle, long long upScaleHandle, long long upWeightHandle, long long outputHandle, int tileSize);
extern int LoomCalculateOptimalGPUTileSizeFromLimits(long long networkHandle, int headDim);
extern char* LoomForwardTokenIDsWGPU(long long transformerHandle, unsigned int* tokens, int numTokens, int computeLogits, int onlyLast);
extern char* LoomForwardWGPU(long long transformerHandle, long long inputHandle);
extern char* LoomNativeGPUParityRowJSON(void);
extern char* LoomWGPUDenseBitNetTernaryParamsJSON(void);
extern char* LoomWGPUBitNetQuantizeActivationParamsJSON(void);
extern char* LoomWGPUDenseBitNetTernaryQuantizedParamsJSON(void);
extern char* LoomWGPUBitNetGateProductParamsJSON(void);
extern char* LoomBitNetShaderNamesJSON(void);
extern char* LoomGPUInfoJSON(void);
extern char* LoomWGPUSoftmaxParamsJSON(void);
extern char* LoomWGPUDenseParamsJSON(void);
extern char* LoomWGPUMHAParamsJSON(void);
extern char* LoomWGPURNNParamsJSON(void);
extern char* LoomWGPULSTMParamsJSON(void);
extern char* LoomWGPUCNN1ParamsJSON(void);
extern char* LoomWGPUCNN2ParamsJSON(void);
extern char* LoomWGPUCNN3ParamsJSON(void);
extern char* LoomWGPURMSNormParamsJSON(void);
extern char* LoomWGPUKVParamsJSON(void);
extern char* LoomWGPURoPEParamsJSON(void);
extern char* LoomWGPUEmbeddingParamsJSON(void);
extern char* LoomWGPUDenseI8ParamsJSON(void);
extern char* LoomWGPUSwiGLUI8ParamsJSON(void);
extern char* LoomWGPUEmbeddingShardParamsJSON(void);
extern char* LoomWGPUMultiHeadSoftmaxCEParamsJSON(void);
extern char* LoomWGPUQuantizeParamsJSON(void);
extern char* LoomWGPUCNN1PackedUpdateParamsJSON(void);
extern char* LoomWGPUCNN1BackwardScaleParamsJSON(void);
extern char* LoomShaderTiledDenseQ4(int tileSize);
extern char* LoomShaderTiledDenseI8(int tileSize);
extern char* LoomShaderTiledDenseN(int tileSize);
extern char* LoomShaderTiledSwiGLUQ4(int tileSize);
extern char* LoomShaderTiledSwiGLUI8(int tileSize);
extern char* LoomShaderTiledSwiGLUN(int tileSize);
extern char* LoomShaderTiledMHAN(int tileSize, int headDim);
extern void LoomCNN1GPUTileSizesForLayer(long long networkHandle, int layerIdx, int dtype, int* scTile, int* mcTile);
extern char* LoomMorphToFloat32ForGPU(long long networkHandle, int layerIdx, int dtype);
extern char* LoomTanhiGPULayerShapeHint(long long networkHandle, int layerIdx, int numTokens);
extern char* LoomDispatchSoftmaxForward(long long networkHandle, int layerIdx, int batchSize, long long inputHandle, long long outputHandle);
extern char* LoomDispatchSoftmaxBackward(long long networkHandle, int batchSize, int size, float temp, long long gradOutputHandle, long long softmaxOutputHandle, long long gradInputHandle);
extern char* LoomDispatchDenseI8(long long networkHandle, int batchSize, int inputSize, int outputSize, long long inputHandle, long long weightHandle, long long outputHandle, float scale, int tileSize);
extern char* LoomDispatchSwiGLUI8(long long networkHandle, int batchSize, int inputSize, int outputSize, long long inputHandle, long long gateWHandle, long long upWHandle, long long gateBiasHandle, long long upBiasHandle, long long outputHandle, float gScale, float uScale, int tileSize);
extern char* LoomDispatchCNN1Packed(long long networkHandle, int dtype, int batchSize, int inC, int inL, int outC, int outL, int kSize, int stride, int padding, float scale, long long inputHandle, long long weightHandle, long long outputHandle);
extern char* LoomDispatchCNN1PackedTiled(long long networkHandle, int dtype, int tileSize, int kernelVol, int batchSize, int inC, int inL, int outC, int outL, int kSize, int stride, int padding, float scale, long long inputHandle, long long weightHandle, long long outputHandle);
extern char* LoomDispatchCNN1PackedBackwardDX(long long networkHandle, int dtype, int batchSize, int inC, int inL, int filters, int outL, int kSize, int stride, int padding, int activation, float scale, long long gradOutHandle, long long weightHandle, long long preActHandle, long long gradInHandle);
extern char* LoomDispatchCNN1PackedBackwardDXTiled(long long networkHandle, int dtype, int tileSize, int kernelVol, int batchSize, int inC, int inL, int filters, int outL, int kSize, int stride, int padding, int activation, float scale, long long gradOutHandle, long long weightHandle, long long preActHandle, long long gradInHandle);
extern char* LoomDispatchCNN1PackedApplyGradients(long long networkHandle, int dtype, int size, float lr, float clipVal, float scale, long long packedHandle, long long gradHandle, long long masterHandle);
extern char* LoomDispatchFillZero(long long networkHandle, int size, long long bufHandle);
extern char* LoomDispatchQuantizeI8(long long networkHandle, int size, float scale, long long masterHandle, long long nativeHandle);
extern char* LoomDispatchQuantizeI4(long long networkHandle, int size, float scale, long long masterHandle, long long nativeHandle);
extern char* LoomDispatchQuantizeFP4(long long networkHandle, int size, float scale, long long masterHandle, long long nativeHandle);
extern char* LoomDispatchQuantizeTernary(long long networkHandle, int size, float scale, long long masterHandle, long long nativeHandle);
extern char* LoomDispatchQuantizeBinary(long long networkHandle, int size, float scale, long long masterHandle, long long nativeHandle);
extern char* LoomDispatchCEGradPartialLoss(long long networkHandle, int size, long long outputHandle, long long targetHandle, long long gradHandle, long long partialsHandle);
extern char* LoomDispatchMultiHeadSoftmaxCEGradPartialLoss(long long networkHandle, int batchSize, int rowWidth, int h0, int h1, int h2, long long outputHandle, long long targetHandle, long long gradHandle, long long partialsHandle);
extern char* LoomDispatchMultiHeadSoftmaxCEGradPartialLossMasked(long long networkHandle, int batchSize, int rowWidth, int h0, int h1, int h2, long long outputHandle, long long targetHandle, long long gradHandle, long long partialsHandle, long long headMaskHandle);
extern long long LoomGetGPUWeightBuffer(long long networkHandle, int layerIdx);
extern char* LoomDispatchDenseBitNetTernary(long long networkHandle, int batchSize, int inputSize, int outputSize, long long inputHandle, long long weightHandle, long long biasHandle, long long outputHandle, float weightScale, int activation, int tileSize);
extern char* LoomDispatchBitNetQuantizeActivation(long long networkHandle, int batchSize, int inputSize, long long inputHandle, long long qPackedHandle, long long scaleHandle);
extern char* LoomDispatchDenseBitNetTernaryQuantized(long long networkHandle, int batchSize, int inputSize, int outputSize, long long qPackedHandle, long long scaleHandle, long long weightHandle, long long biasHandle, long long outputHandle, float weightScale, int activation, int tileSize);
extern char* LoomDispatchBitNetGateProduct(long long networkHandle, int batchSize, int hiddenSize, int activation, long long gatePreHandle, long long upPreHandle, long long outputHandle);
extern char* LoomRunNativeLayerMatrix(char* configJSON);
extern int LoomCalculateOptimalCNN1TileSizeForLayer(long long networkHandle, int layerIdx, int dtype);
extern char* LoomCNN1ForwardPackedCPUFloat32(long long networkHandle, int layerIdx, char* inputJSON);
extern char* LoomCNN1BackwardPackedCPUFloat32(long long networkHandle, int layerIdx, char* gradOutputJSON, char* inputJSON, char* preActJSON);
extern char* LoomMHABackwardTiledFloat32(long long networkHandle, int layerIdx, char* gradOutputJSON, char* inputJSON, char* preActJSON);
extern char* LoomLoadSafetensorsSelectiveFromBytes(char* buffer, int length, char* tensorNamesJSON);
extern char* LoomSaveSafetensorsToBytes(long long networkHandle);
extern char* LoomApplyGradientsNative(long long networkHandle, int layerIdx, int dtype, char* gradWeightsJSON, float learningRate, float clipVal);
extern char* LoomLoadEOSTokenIDsFromConfigPath(char* path);
extern long long LoomNewTokenizerFromJSON(char* buffer, int length);
extern char* LoomSystemAuditToJSON(long long networkHandle);
extern int LoomAsmEnabled(void);
extern char* LoomSetNetworkUseAsmForward(long long networkHandle, int enabled);
extern int LoomGetNetworkUseAsmForward(long long networkHandle);
extern char* LoomSetLayerUseAsmForward(long long networkHandle, int layerIndex, int enabled);
extern int LoomGPUPackedWeightsKey(int dtype);
extern int LoomGPUPackedNativeByteSize(int dtype, int weightCount);
extern int LoomStoredTensorNumElements(char* tensorJSON);
extern char* LoomDecodeTensorBytesInto(char* dstJSON, char* bytesJSON, char* dtype);
extern char* LoomLoadSafetensorsSelectiveRawFromBytes(char* buffer, int length, char* tensorNamesJSON);
extern char* LoomSetLayerLoadedWeights(long long networkHandle, int layerIndex, int dtype, char* weightsJSON);
extern char* LoomMorphLayerBitNetTernary(long long networkHandle, int layerIndex);
extern char* LoomMorphLayerBitNetNativeTernary(long long networkHandle, int layerIndex);
extern char* LoomDenseForwardPackedTernaryCPU(long long networkHandle, int layerIndex, char* inputJSON);
extern char* LoomMHAForwardPackedTernaryCPU(long long networkHandle, int layerIndex, char* inputJSON);
extern char* LoomSwiGLUForwardPackedTernaryCPU(long long networkHandle, int layerIndex, char* inputJSON);
extern char* LoomMorphToFloat32ForGPUMasterSlice(long long networkHandle, int layerIndex, int dtype, char* masterJSON);
extern char* LoomDefaultSpliceConfig(void);
extern long long LoomSpliceDNA(long long handleA, long long handleB, char* cfgJSON);
extern char* LoomSpliceDNAWithReport(long long handleA, long long handleB, char* cfgJSON);
extern char* LoomDefaultNEATConfig(int dModel);
extern long long LoomNEATMutate(long long handle, char* cfgJSON);
extern long long LoomNewNEATPopulation(long long seedHandle, int size, char* cfgJSON);
extern int LoomNEATPopulationSize(long long popHandle);
extern long long LoomNEATPopulationGetNetwork(long long popHandle, int index);
extern char* LoomNEATPopulationEvolveWithFitnesses(long long popHandle, char* fitnessesJSON);
extern long long LoomNEATPopulationBest(long long popHandle);
extern double LoomNEATPopulationBestFitness(long long popHandle);
extern char* LoomNEATPopulationSummary(long long popHandle, int generation);
extern void LoomFreeNEATPopulation(long long popHandle);
extern long long LoomCreateGPUBuffer(long long networkHandle, long long sizeBytes);
extern void LoomFreeGPUBuffer(long long bufHandle);
extern char* LoomWriteGPUBuffer(long long networkHandle, long long bufHandle, float* data, int length);
extern char* LoomReadGPUBuffer(long long networkHandle, long long bufHandle);
extern char* LoomShaderDenseBackwardDX(int tileSize);
extern char* LoomShaderDenseBackwardDW(int tileSize);
extern char* LoomDispatchDenseBackwardDX(long long networkHandle, int batchSize, int inputSize, int outputSize, long long gradOutputHandle, long long weightHandle, long long gradInputHandle, int tileSize);
extern char* LoomDispatchDenseBackwardDW(long long networkHandle, int batchSize, int inputSize, int outputSize, long long gradOutputHandle, long long inputHandle, long long gradWeightHandle, int tileSize);
extern char* LoomDispatchSwiGLUBackward(long long networkHandle, int batchSize, int inputSize, int outputSize, long long gradOutputHandle, long long gateInHandle, long long upInHandle, long long gradGateHandle, long long gradUpHandle);
extern char* LoomDispatchRMSNormBackward(long long networkHandle, int batchSize, int size, float epsilon, long long gradOutputHandle, long long inputHandle, long long rmsHandle, long long weightHandle, long long gradInputHandle, long long gradWeightHandle);
extern char* LoomDispatchEmbeddingBackward(long long networkHandle, int vocabSize, int hiddenSize, int numTokens, long long indicesHandle, long long gradOutputHandle, long long gradWeightHandle);
extern char* LoomDispatchResidualBackward(long long networkHandle, int size, long long gradOutputHandle, long long gradInputHandle, long long gradResidualHandle);
extern char* LoomDispatchCNN1BackwardDX(long long networkHandle, int batchSize, int inC, int inL, int filters, int outL, int kSize, int stride, int padding, int activation, long long gradOutputHandle, long long weightHandle, long long preActHandle, long long gradInputHandle);
extern char* LoomDispatchCNN1BackwardDW(long long networkHandle, int batchSize, int inC, int inL, int filters, int outL, int kSize, int stride, int padding, int activation, long long gradOutputHandle, long long inputHandle, long long preActHandle, long long gradWeightHandle);
extern char* LoomDispatchCNN2BackwardDX(long long networkHandle, int batchSize, int inC, int inH, int inW, int filters, int outH, int outW, int kSize, int stride, int padding, int activation, long long gradOutputHandle, long long weightHandle, long long preActHandle, long long gradInputHandle);
extern char* LoomDispatchCNN2BackwardDW(long long networkHandle, int batchSize, int inC, int inH, int inW, int filters, int outH, int outW, int kSize, int stride, int padding, int activation, long long gradOutputHandle, long long inputHandle, long long preActHandle, long long gradWeightHandle);
extern char* LoomDispatchCNN3BackwardDX(long long networkHandle, int batchSize, int inC, int inD, int inH, int inW, int filters, int outD, int outH, int outW, int kSize, int stride, int padding, int activation, long long gradOutputHandle, long long weightHandle, long long preActHandle, long long gradInputHandle);
extern char* LoomDispatchCNN3BackwardDW(long long networkHandle, int batchSize, int inC, int inD, int inH, int inW, int filters, int outD, int outH, int outW, int kSize, int stride, int padding, int activation, long long gradOutputHandle, long long inputHandle, long long preActHandle, long long gradWeightHandle);
extern char* LoomDispatchMHABackward(long long networkHandle, int batchSize, int numHeads, int numKVHeads, int headDim, int seqLen, float scale, long long gradOutputHandle, long long qHandle, long long kHandle, long long vHandle, long long dQHandle, long long dKHandle, long long dVHandle);
extern char* LoomDispatchApplyGradients(long long networkHandle, int size, float lr, long long weightHandle, long long gradHandle);
extern char* LoomDispatchMSEGradPartialLoss(long long networkHandle, int size, long long outputHandle, long long targetHandle, long long gradHandle, long long partialsHandle);
extern char* LoomDispatchForwardLayer(long long networkHandle, int layerIdx, int batchSize, long long inputHandle, long long outputHandle);
extern char* LoomDispatchBackwardLayer(long long networkHandle, int layerIdx, int batchSize, long long gradOutHandle, long long inputHandle, long long preActHandle, long long dxHandle, long long dwHandle);
extern char* LoomDispatchActivation(long long networkHandle, int size, int activation, long long inputHandle, long long outputHandle);
extern char* LoomDispatchActivationBackward(long long networkHandle, int size, int activation, long long gradOutHandle, long long preActHandle, long long gradInHandle);
extern char* LoomShaderTiledDenseBackwardDX(int tileSize);
extern char* LoomShaderTiledDenseBackwardDW(int tileSize);
extern char* LoomShaderTiledRNNBackwardDX(int tileSize);
extern char* LoomShaderTiledRNNBackwardDW(int tileSize);
extern char* LoomShaderTiledLSTMBackwardDX(int tileSize);
extern char* LoomShaderTiledLSTMBackwardDW(int tileSize);
extern char* LoomShaderTiledCNN1BackwardDX(int tileSize);
extern char* LoomShaderTiledCNN1BackwardDW(int tileSize);
extern char* LoomShaderTiledCNN2BackwardDX(int tileSize, int kernelVol);
extern char* LoomShaderTiledCNN2BackwardDW(int tileSize);
extern char* LoomShaderTiledCNN3BackwardDX(int tileSize, int kernelVol);
extern char* LoomShaderTiledCNN3BackwardDW(int tileSize);
extern int LoomDispatchDenseBackwardDXTiled(long long ctxHandle, int tileSize, int batchSize, int inputSize, int outputSize, unsigned int activation, long long gradOutputHandle, long long weightHandle, long long preActHandle, long long gradInputHandle);
extern int LoomDispatchDenseBackwardDWTiled(long long ctxHandle, int tileSize, int batchSize, int inputSize, int outputSize, unsigned int activation, long long gradOutputHandle, long long inputHandle, long long preActHandle, long long gradWeightsHandle);
extern int LoomDispatchRNNBackwardDX(long long ctxHandle, int tileSize, int batchSize, int inputSize, int hiddenSize, long long gradOutHandle, long long weightHandle, long long preActHandle, long long dxHandle);
extern int LoomDispatchRNNBackwardDW(long long ctxHandle, int tileSize, int batchSize, int inputSize, int hiddenSize, long long gradOutHandle, long long inputHandle, long long preActHandle, long long hPrevHandle, long long dwHandle);
extern int LoomDispatchLSTMBackwardDX(long long ctxHandle, int tileSize, int batchSize, int inputSize, int hiddenSize, long long gradOutHandle, long long weightHandle, long long preActHandle, long long dxHandle);
extern int LoomDispatchLSTMBackwardDW(long long ctxHandle, int tileSize, int batchSize, int inputSize, int hiddenSize, long long gradOutHandle, long long inputHandle, long long preActHandle, long long hPrevHandle, long long dwHandle);
extern int LoomDispatchCNN1TiledBackwardDX(long long ctxHandle, int batchSize, int inC, int inL, int filters, int outL, int kSize, int stride, int padding, unsigned int activation, long long gradOutHandle, long long weightHandle, long long preActHandle, long long dxHandle);
extern int LoomDispatchCNN1TiledBackwardDW(long long ctxHandle, int batchSize, int inC, int inL, int filters, int outL, int kSize, int stride, int padding, unsigned int activation, long long gradOutHandle, long long inputHandle, long long preActHandle, long long dwHandle);
extern int LoomDispatchCNN2TiledBackwardDX(long long ctxHandle, int batchSize, int inC, int ih, int iw, int filters, int oh, int ow, int kSize, int stride, int padding, unsigned int activation, long long gradOutHandle, long long weightHandle, long long preActHandle, long long dxHandle);
extern int LoomDispatchCNN2TiledBackwardDW(long long ctxHandle, int batchSize, int inC, int ih, int iw, int filters, int oh, int ow, int kSize, int stride, int padding, unsigned int activation, long long gradOutHandle, long long inputHandle, long long preActHandle, long long dwHandle);
extern int LoomDispatchCNN3TiledBackwardDX(long long ctxHandle, int batchSize, int inC, int id, int ih, int iw, int filters, int od, int oh, int ow, int kSize, int stride, int padding, unsigned int activation, long long gradOutHandle, long long weightHandle, long long preActHandle, long long dxHandle);
extern int LoomDispatchCNN3TiledBackwardDW(long long ctxHandle, int batchSize, int inC, int id, int ih, int iw, int filters, int od, int oh, int ow, int kSize, int stride, int padding, unsigned int activation, long long gradOutHandle, long long inputHandle, long long preActHandle, long long dwHandle);
extern long long LoomCreateStepState(long long networkHandle, int dtype);
extern void LoomFreeStepState(long long handle);
extern void LoomSetInput(long long stateHandle, float* data, int length);
extern long long LoomStep(long long networkHandle, long long stateHandle, int captureHistory);
extern char* LoomGetOutput(long long stateHandle, int layerIdx);
extern char* LoomSequentialForward(long long networkHandle, float* inputData, int inputLen);
extern char* LoomConfigureTrainingMode(long long networkHandle, int mode);
extern char* LoomForwardPolymorphic(long long networkHandle, float* inputData, int inputLen, char* shapeJSON);
extern char* LoomBackwardPolymorphic(long long networkHandle, float* inputData, int inputLen, char* inputShapeJSON, float* targetData, int targetLen, char* targetShapeJSON);
extern char* LoomMorphLayer(long long networkHandle, int layerIdx, int targetDType);
extern long long LoomTokensToTensor(long long transformerHandle, unsigned int* tokens, int count);
extern long long LoomForwardFull(long long transformerHandle, long long inputTensorHandle);
extern void LoomFreeTensor(long long handle);
extern char* LoomLoadSafetensorsWithShapes(char* path);
extern long long LoomBuildNetworkFromJSON(char* jsonConfig);
extern long long LoomCreateNetwork(char* jsonConfig);
extern long long LoomLoadUniversal(char* path);
extern void LoomFreeNetwork(long long handle);
extern char* LoomLoadWithPrefixes(long long networkHandle, char* path);
extern char* LoomGetNetworkInfo(long long handle);
extern char* LoomExtractDNA(long long networkHandle);
extern char* LoomExtractNetworkBlueprint(long long networkHandle, char* modelID);
extern char* LoomCompareDNA(char* dna1JSON, char* dna2JSON);
extern char* LoomSaveSafetensors(char* path, char* tensorsJSON);
extern char* LoomGetMethodsJSON(void);
extern char* LoomLoadSafetensors(char* path);
extern char* LoomLoadSafetensorsFromBytes(char* buffer, int length);
extern char* LoomGetLayerTelemetry(long long networkHandle, int layerIdx);
extern char* LoomLoadUniversalDetailed(char* path);
extern long long LoomCreateTransformer(long long networkHandle, char* embeddingsJSON, char* lmHeadJSON, char* finalNormJSON);
extern char* LoomDenseForward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomRMSNormForward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomLayerNormForward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomMHAForward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomSoftmaxForward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomSwiGLUForward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomEmbeddingForward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomResidualForward(long long networkHandle, int layerIdx, long long inputHandle, long long skipHandle);
extern char* LoomKMeansForward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomRNNForward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomLSTMForward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomCNN1Forward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomCNN2Forward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomCNN3Forward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomConvTransposed1DForward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomConvTransposed2DForward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomConvTransposed3DForward(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomDenseForwardTiled(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomCNN1ForwardTiled(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomCNN2ForwardTiled(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomCNN3ForwardTiled(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomRNNForwardTiled(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomLSTMForwardTiled(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomMHAForwardTiled(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomSwiGLUForwardTiled(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomEmbeddingForwardTiled(long long networkHandle, int layerIdx, long long inputHandle);
extern char* LoomResidualForwardTiled(long long networkHandle, int layerIdx, long long inputHandle, long long skipHandle);
extern char* LoomCNN1BackwardTiled(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomCNN2BackwardTiled(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomCNN3BackwardTiled(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomRNNBackwardTiled(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomLSTMBackwardTiled(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomParallelBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomSwiGLUBackwardTiled(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomEmbeddingBackwardTiled(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomResidualBackwardTiled(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern void LoomInitLayerNormCell(long long networkHandle, int z, int y, int x, int l, int size, int dtype);
extern char* LoomDispatchLayer(long long networkHandle, int layerIdx, long long inputHandle, long long skipHandle);
extern char* LoomDispatchLayerBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long skipHandle, long long preActHandle);
extern long long LoomNewVolumetricNetwork(int depth, int rows, int cols, int layersPerCell);
extern char* LoomComputeLayerStats(long long tensorHandle);
extern char* LoomLLMListModels(char* hubDirC);
extern char* LoomLLMListInstalledModels(char* hubDirC);
extern long long LoomCreateLLM(char* snapshotDirC, int execMode, int precisionInt, int useGPUInt, int deterministicInt);
extern char* LoomLLMGenerate(long long handle, char* systemPromptC, char* userMsgC, float temperatureF, int topKI, int maxTokensI);
extern void LoomLLMStartGenerate(long long handle, char* systemPromptC, char* userMsgC, float temperatureF, int topKI, int maxTokensI);
extern char* LoomLLMPollToken(long long handle);
extern void LoomLLMResetHistory(long long handle);
extern void LoomFreeLLM(long long handle);
extern void FreeLoomString(char* ptr);
extern char* LoomSerializeNetwork(long long networkHandle);
extern long long LoomDeserializeNetwork(char* jsonBuf, int length);
extern char* LoomLayerPersistenceFromJSON(char* jsonBuf, int length, int layerIndex);
extern char* LoomLayerNativePersistenceSnapshot(long long networkHandle, int layerIndex, int dtype);
extern LoomLayerSpec LoomGetLayerSpec(long long networkHandle, int layerIdx);
extern LoomLayerStats LoomGetLayerStats(long long stateHandle, int layerIdx);
extern void LoomNetworkTanhiConfigure(long long handle, int enabled, char* hostC, int port, int sendShape);
extern void LoomNetworkTanhiDisable(long long handle);
extern int LoomTanhiDefaultPort(void);
extern long long LoomLoadTokenizer(char* path);
extern char* LoomTokenize(long long handle, char* text);
extern char* LoomDetokenize(long long handle, char* tokensJSON);
extern void LoomFreeTokenizer(long long handle);
extern void LoomApplyGradients(long long networkHandle, int layerIdx, char* gradWeightsJSON, float learningRate);
extern char* LoomStepBackward(long long networkHandle, long long stateHandle, float* gradOutputData, int gradOutputLen);
extern void LoomApplyTween(long long networkHandle, long long stateHandle, float* targetData, int targetLen, float learningRate);
extern long long LoomCreateTweenState(long long networkHandle, int dtype);
extern char* LoomTweenForward(long long networkHandle, long long tpHandle, float* inputData, int inputLen);
extern void LoomTweenBackward(long long networkHandle, long long tpHandle, float* targetData, int targetLen);
extern char* LoomDefaultTweenConfig(void);
extern void LoomApplyTweenGaps(long long networkHandle, long long tpHandle, float learningRate);
extern char* LoomComputeLossGradient(long long outputHandle, long long targetHandle, char* lossType);
extern char* LoomTrain(long long networkHandle, float* inputData, int inputLen, float* targetData, int targetLen, int batchSize, int inDim, int outDim, char* configJSON);
extern char* LoomDenseBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomRMSNormBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomLayerNormBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomMHABackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomSoftmaxBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long postActHandle);
extern char* LoomSwiGLUBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomEmbeddingBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomResidualBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomKMeansBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomRNNBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomLSTMBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomCNN1Backward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomCNN2Backward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomCNN3Backward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomConvTransposed1DBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomConvTransposed2DBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern char* LoomConvTransposed3DBackward(long long networkHandle, int layerIdx, long long gradOutputHandle, long long inputHandle, long long preActHandle);
extern void LoomTweenBackwardChainRule(long long networkHandle, long long tpHandle, long long targetHandle);
extern void LoomTweenBackwardLayerwise(long long networkHandle, long long tpHandle, long long targetHandle);
extern void LoomApplyRecursiveGradients(long long networkHandle, int layerIdx, char* gradWeightsJSON, float learningRate);
extern char* LoomSetTransformerForwardMode(long long transformerHandle, int mode);
extern int LoomGetTransformerForwardMode(long long transformerHandle);
extern int LoomTransformerCPUForwardQueueStepTotal(long long transformerHandle);
extern char* LoomTransformerBeginCPUForwardQueue(long long transformerHandle, char* inputJSON);
extern char* LoomTransformerCPUForwardQueueTick(long long transformerHandle);
extern char* LoomTransformerCPUForwardQueueResult(long long transformerHandle);
extern char* LoomTransformerCPUForwardQueueDiscard(long long transformerHandle);
extern char* LoomTransformerComparePrefillToNormal(long long transformerHandle, char* inputJSON);
extern char* LoomTransformerTakePipelineForwardStats(long long transformerHandle);
extern char* LoomTransformerLastPipelineForwardStats(long long transformerHandle);
extern char* LoomForwardBenchResultJSON(void);
extern char* LoomLayerActionRecordJSON(void);
extern char* LoomSetTransformerForwardStepObserver(long long transformerHandle, int debug);
extern char* LoomTransformerLayerTraceRecords(long long transformerHandle);

#ifdef __cplusplus
}
#endif
