#!/usr/bin/env bash
# Download OpenVINO C++ toolkit into deps/ (no sudo) and write setup_env.sh.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
DEPS="${ROOT}/deps"
OV_VERSION="${OV_VERSION:-2025.4.0}"
BUILD="${OV_BUILD:-20398.8fdad55727d}"

OS="$(uname -s)"
ARCH="$(uname -m)"
case "$OS" in
  Linux)
    PKG_ROOT="linux"
    case "$ARCH" in
      x86_64|amd64) DISTRO="${OV_DISTRO:-rhel8}" ;;
      aarch64|arm64) DISTRO="${OV_DISTRO:-rhel8}" ;;
      *) echo "Unsupported Linux arch: $ARCH" >&2; exit 1 ;;
    esac
    TGZ="openvino_toolkit_${DISTRO}_${OV_VERSION}.${BUILD}_${ARCH}.tgz"
    EXTRACTED="openvino_toolkit_${DISTRO}_${OV_VERSION}.${BUILD}_${ARCH}"
    ;;
  Darwin)
    PKG_ROOT="macos"
    case "$ARCH" in
      arm64)  OV_ARCH="arm64" ;;
      x86_64) OV_ARCH="x86_64" ;;
      *) echo "Unsupported macOS arch: $ARCH" >&2; exit 1 ;;
    esac
    TGZ="openvino_toolkit_macos_${OV_VERSION}.${BUILD}_${OV_ARCH}.tgz"
    EXTRACTED="openvino_toolkit_macos_${OV_VERSION}.${BUILD}_${OV_ARCH}"
    ;;
  *)
    echo "Unsupported OS: $OS (need Linux or macOS)" >&2
    exit 1
    ;;
esac

URL="https://storage.openvinotoolkit.org/repositories/openvino/packages/2025.4/${PKG_ROOT}/${TGZ}"
OV_DIR="${DEPS}/${EXTRACTED}"

mkdir -p "$DEPS"

if [[ ! -f "${DEPS}/${TGZ}" ]]; then
  echo "Downloading ${URL} ..."
  curl -fL --retry 3 -o "${DEPS}/${TGZ}" "$URL"
fi

if [[ ! -d "${OV_DIR}" ]]; then
  echo "Extracting to ${DEPS}/ ..."
  tar -xf "${DEPS}/${TGZ}" -C "$DEPS"
fi

if [[ ! -f "${OV_DIR}/setupvars.sh" ]]; then
  echo "Expected ${OV_DIR}/setupvars.sh after extract." >&2
  exit 1
fi

cat > "${ROOT}/setup_env.sh" <<EOF
#!/usr/bin/env bash
# Generated by install_openvino.sh — source before cmake / go run.
export INTEL_OPENVINO_DIR="${OV_DIR}"
# setupvars.sh references unset vars when Python 3.10+ is missing; disable nounset briefly.
set +u
# shellcheck disable=SC1091
source "\${INTEL_OPENVINO_DIR}/setupvars.sh"
set +u
if [[ "\$(uname -s)" == Linux ]]; then
  # System NPU UMD (dnf install intel-npu-driver). Compiler: ./install_npu_compiler.sh
  export LD_LIBRARY_PATH="/usr/lib64:\${LD_LIBRARY_PATH:-}"
fi
EOF
chmod +x "${ROOT}/setup_env.sh"

echo "Wrote ${ROOT}/setup_env.sh  (INTEL_OPENVINO_DIR=${OV_DIR})"
echo
echo "Next:"
echo "  cd ${ROOT}"
echo "  source ./setup_env.sh"
echo "  ./build.sh"
if [[ "$OS" == Darwin ]]; then
  echo
  echo "Note: Intel NPU plugin is Linux-only. macOS build exercises OpenVINO CPU path only."
  echo "      Run accel/intel/example on Linux for full CPU vs NPU demo."
fi
