# install_qairt.ps1 — fetch the freely-redistributable QAIRT (QNN) HTP runtime for
# Windows-on-Snapdragon into deps/, detect the full QAIRT SDK for headers, and
# write setup_env.ps1. Mirrors accel/intel/install_openvino.sh.
#
#   pwsh -File .\install_qairt.ps1
#
# The full SDK (QNN headers + QnnCpu.dll reference backend + tools) is only
# available from the Qualcomm Software Center (free login). Install it, then this
# script auto-detects it under C:\Qualcomm\AIStack\QAIRT\<version>.

param(
    # Persist QNN_SDK_ROOT / LOOM_QUALCOMM_RUNTIME so every shell and every user
    # picks them up on login (not just the current session). Machine scope needs
    # an elevated shell; otherwise it falls back to User scope.
    [switch]$Persist
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$Deps = Join-Path $Root 'deps'
New-Item -ItemType Directory -Force -Path $Deps | Out-Null

# --- 1. Free HTP runtime (backend DLLs + signed Hexagon v73 skel/cat) ---------
$RuntimeVersion = '2.38.0'
$RuntimeZip = Join-Path $Deps "QAIRT_Runtime_${RuntimeVersion}_v73.zip"
$RuntimeUrl = "https://github.com/qualcomm/qai-appbuilder/releases/download/v${RuntimeVersion}/QAIRT_Runtime_${RuntimeVersion}_v73.zip"
$RuntimeDir = Join-Path $Deps 'qairt-runtime'

if (-not (Test-Path $RuntimeZip)) {
    Write-Host "Downloading QAIRT runtime $RuntimeVersion ..."
    curl.exe -sL --retry 3 -o $RuntimeZip $RuntimeUrl
}
if (-not (Test-Path $RuntimeDir)) {
    Write-Host "Extracting runtime to $RuntimeDir ..."
    Expand-Archive -Path $RuntimeZip -DestinationPath $RuntimeDir -Force
}

# aarch64-windows-msvc holds the native ARM64 backend set.
$RuntimeLibDir = Join-Path $RuntimeDir 'aarch64-windows-msvc'
if (-not (Test-Path (Join-Path $RuntimeLibDir 'QnnHtp.dll'))) {
    Write-Warning "QnnHtp.dll not found under $RuntimeLibDir - runtime layout changed?"
}

# --- 2. Full QAIRT SDK (headers + QnnCpu.dll + tools) -------------------------
$SdkRoot = $env:QNN_SDK_ROOT
if (-not $SdkRoot -or -not (Test-Path $SdkRoot)) {
    $base = 'C:\Qualcomm\AIStack\QAIRT'
    if (Test-Path $base) {
        $SdkRoot = (Get-ChildItem $base -Directory | Sort-Object Name | Select-Object -Last 1).FullName
    }
}
# Vendored SDK under accel/qualcomm/deps/ (what we used on the Snapdragon dev box).
if (-not $SdkRoot -or -not (Test-Path (Join-Path $SdkRoot 'include\QNN\QnnInterface.h'))) {
    $vendored = Join-Path $Deps 'qairt-sdk\qairt'
    if (Test-Path $vendored) {
        $SdkRoot = (Get-ChildItem $vendored -Directory | Sort-Object Name | Select-Object -Last 1).FullName
    }
}

$haveHeaders = $false
if ($SdkRoot -and (Test-Path (Join-Path $SdkRoot 'include\QNN\QnnInterface.h'))) {
    $haveHeaders = $true
}

# --- 3. Write setup_env.ps1 ---------------------------------------------------
$setup = Join-Path $Root 'setup_env.ps1'
$lines = @(
    '# Generated by install_qairt.ps1 - dot-source before cmake / go run:  . .\setup_env.ps1'
)
if ($SdkRoot) { $lines += "`$env:QNN_SDK_ROOT = '$SdkRoot'" }
$lines += "`$env:LOOM_QUALCOMM_RUNTIME = '$RuntimeLibDir'"
# Put the HTP backend DLLs on PATH so LoadLibrary('QnnHtp.dll') resolves.
$lines += "`$env:PATH = '$RuntimeLibDir' + [IO.Path]::PathSeparator + `$env:PATH"
if ($SdkRoot) {
    $lines += "`$env:PATH = (Join-Path `$env:QNN_SDK_ROOT 'lib\aarch64-windows-msvc') + [IO.Path]::PathSeparator + `$env:PATH"
}
Set-Content -Path $setup -Value ($lines -join "`r`n") -Encoding UTF8

Write-Host ''
Write-Host "Runtime libs: $RuntimeLibDir"
if ($haveHeaders) {
    Write-Host "QAIRT SDK:    $SdkRoot  (headers found)"
} else {
    Write-Warning "Full QAIRT SDK not found. To BUILD the plugin you need QNN headers."
    Write-Host  "  1. Download 'Qualcomm AI Runtime SDK' from https://softwarecenter.qualcomm.com (free login)"
    Write-Host  "  2. Install it (defaults to C:\Qualcomm\AIStack\QAIRT\<version>)"
    Write-Host  "  3. Re-run this script, or set `$env:QNN_SDK_ROOT manually."
}
Write-Host ''
Write-Host "Wrote $setup"

# --- 4. Persist for all users (optional) --------------------------------------
# The plugin loader (PrepareQualcommRuntime) prepends $QNN_SDK_ROOT\lib\aarch64-
# windows-msvc to PATH at runtime, so persisting QNN_SDK_ROOT is enough for a
# fresh login / another user to resolve QnnCpu.dll / QnnHtp.dll.
if ($Persist) {
    $scope = 'Machine'
    $isAdmin = ([Security.Principal.WindowsPrincipal] `
        [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
        [Security.Principal.WindowsBuiltinRole]::Administrator)
    if (-not $isAdmin) {
        Write-Warning "Not elevated - persisting to User scope only (run as admin for all users)."
        $scope = 'User'
    }
    if ($SdkRoot) {
        [Environment]::SetEnvironmentVariable('QNN_SDK_ROOT', $SdkRoot, $scope)
        Write-Host "Persisted QNN_SDK_ROOT ($scope) = $SdkRoot"
    }
    [Environment]::SetEnvironmentVariable('LOOM_QUALCOMM_RUNTIME', $RuntimeLibDir, $scope)
    Write-Host "Persisted LOOM_QUALCOMM_RUNTIME ($scope) = $RuntimeLibDir"
    Write-Host "Open a new shell for the persisted values to take effect."
} else {
    Write-Host "Tip: re-run with -Persist (elevated) to set these for ALL users on login."
}

Write-Host ''
Write-Host "Next:  . .\setup_env.ps1  ;  .\build_clang.ps1   (or build.ps1 if CMake is installed)"
